export * from './types.js';
export { computeBoundingBox, EMPTY_BOUNDING_BOX } from './bounding-box.js';
export type { BoundingBox } from './bounding-box.js';
export { resolveContentGeometry, contentKindOf, contentLabel } from './content.js';
export type { ContentKind, ContentStatus, ContentResolution } from './content.js';
export { resolveDoorGeometry } from './doors.js';
export type { DoorStatus, DoorLeafGeometry, DoorGeometryResolution } from './doors.js';
export { resolveDrawerFacadeGeometry } from './drawers.js';
export type { DrawerFacadeStatus, DrawerFacadeGeometry, DrawerFacadeGeometryResolution } from './drawers.js';
export { findPartOverlaps } from './overlaps.js';
export type { PartOverlap } from './overlaps.js';
export { GeometryContext } from './context.js';
export type { GeometryStage } from './context.js';
export { buildGeometry, PIPELINE } from './engine.js';
export { makePart, rawCutSize, applyEdgeSizing, edgeKey, resolveMaterial } from './parts.js';
export { resolveBackGeometry } from './stages/carcass.js';
export { layoutStage } from './stages/layout.js';
export { facadesStage } from './stages/facades.js';
